# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key

from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
vacation_df = pd.read_csv('Weather dataframe')
vacation_df.head()

,Unnamed: 0,city,latitude,longitude,temperature,humidity,cloudiness,wind speed
0,0,ushuaia,-54.80,-68.30,278.15,56,75,75
1,1,rikitea,-23.12,-134.97,294.04,77,0,0
2,2,clyde river,70.47,-68.59,279.92,68,2,2
3,3,visby,57.64,18.30,289.35,45,0,0
4,4,budhlada,29.93,75.57,301.97,71,8,8

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [8]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)
# Store 'Lat' and 'Lng' into  locations 
locations = vacation_df[["latitude", "longitude"]].astype(float)
humidity_measure = vacation_df["humidity"].astype(float)

locations.head()

   latitude  longitude
0    -54.80     -68.30
1    -23.12    -134.97
2     70.47     -68.59
3     57.64      18.30
4     29.93      75.57

In [4]:

# Create a Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_measure, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 4)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
vacation_drop = vacation_df.dropna()
vacation_drop.head()

,Unnamed: 0,city,latitude,longitude,temperature,humidity,cloudiness,wind speed
0,0,ushuaia,-54.80,-68.30,278.15,56,75,75
1,1,rikitea,-23.12,-134.97,294.04,77,0,0
2,2,clyde river,70.47,-68.59,279.92,68,2,2
3,3,visby,57.64,18.30,289.35,45,0,0
4,4,budhlada,29.93,75.57,301.97,71,8,8

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
# set up additional columns to hold information
vacation_drop['name'] = ""
vacation_drop['address'] = ""
vacation_drop['price_level'] = ""
vacation_drop['rating'] = ""

vacation_drop.head()

,Unnamed: 0,city,latitude,longitude,temperature,humidity,cloudiness,wind speed,name,address,price_level,rating
0,0,ushuaia,-54.80,-68.30,278.15,56,75,75,,,,
1,1,rikitea,-23.12,-134.97,294.04,77,0,0,,,,
2,2,clyde river,70.47,-68.59,279.92,68,2,2,,,,
3,3,visby,57.64,18.30,289.35,45,0,0,,,,
4,4,budhlada,29.93,75.57,301.97,71,8,8,,,,

In [26]:
# find the closest restaurant of each type to coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 500, 
    "rankby": "distance",
    "type": "Hotel Name",
    "key": g_key,
}

# use iterrows to iterate through pandas dataframe
for index, row in vacation_drop.iterrows():

    # get hotel from df
    vaca_hotels = row['city']
    
    lat = row["latitude"]
    lng = row["longitude"]

    # add keyword to params dict
    params['location'] = f"{lat},{lng}"
    
    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {vaca_hotels}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    print(results)
    
#     try:
#         print(f"Closest {vaca_hotels} hotels is {results[0]['hotel']}.")
        
# #         vacation_drop.loc[index, 'name'] = results[0]['name']
# #         vacation_drop.loc[index, 'address'] = results[0]['vicinity']
# #         vacation_drop.loc[index, 'price_level'] = results[0]['price_level']
# #         vacation_drop.loc[index, 'rating'] = results[0]['rating']
        
#     except (KeyError, IndexError):
#         print("Missing field/result... skipping.")
        
#     print("------------")

Retrieving Results for Index 0: ushuaia.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 1: rikitea.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 2: clyde river.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 3: visby.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 4: budhlada.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 5: saskylakh.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 6: chara.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 7: yagunovskiy.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 8: port alfred.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 9: ipixuna.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 10: butaritari.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 11: geraldton.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 12: albany.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 13: hobart.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 14: kwekwe.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 15: busselton.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 16: kapaa.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 17: castro.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 18: east london.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 19: vestmannaeyjar.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 20: victoria.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 21: hermanus.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 22: bluff.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 23: tauramena.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 24: tuktoyaktuk.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 25: bambous virieux.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 26: salta.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 27: veraval.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 28: iqaluit.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 29: port elizabeth.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 30: hithadhoo.
[]
Missing field/result... skipping.
------------
Retrieving Results for Index 31: qaanaaq.

KeyboardInterrupt:

In [39]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
vacation_drop = [info_box_template.format(**row) for index, row in vacation_drop.iterrows()]
locations = vacation_drop[["Lat", "Lng"]]

KeyError: 'Hotel Name'

In [ ]:
coordinates

# Add marker layer ontop of heat map
markers = gmaps.marker_layer(coordinates)

# Display figure
fig.add_layer(markers)
fig